[package]
name = "verishda-slint"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.4"
winreg = "0.52"
anyhow = "1.0"
tokio = {version="1.36.0", features=["full"]}
openidconnect = "3.5.0"
url = "2.5.0"
serde = {verion="1.0.197", features=["derive"]}
serde_json = "1.0.114"
tokio-serde = { version = "0.9.0", features = ["json"] }
tokio-util = "0.7.10"
json = "0.12.4"
futures = "0.3.30"

[build-dependencies]
slint-build = "1.4"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }

