[package]
name = "hoozin-server"
authors = ["Pachler, Uwe <uwe.pachler@datagroup.de>"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
# Useful crate to handle errors.
anyhow = "1"
thiserror = "1.0.40"
# Crate to simplify working with bytes.
bytes = "1"
# General-purpose crate with common HTTP types.
http = "0.2"
# The Spin SDK.
spin-sdk = { git = "https://github.com/lann/spin.git", branch="sdk-error-pub"}
# Crate that generates Rust Wasm bindings from a WebAssembly interface.
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "cb871cfa1ee460b51eb1d144b175b9aab9c50aba" }

serde = {version="1.0.160", features=["derive"]}
serde_json = "1.0.96"
openidconnect = {version="3.0.0", default-features = false}

[workspace]