[workspace]
resolver = "2"

members = [
    "verishda-server",
    "verishda-slint",
    "verishda-dto",
]

[patch.crates-io]

postgres-protocol = {git="https://github.com/sfackler/rust-postgres.git", branch="master"}
tokio-postgres = {git="https://github.com/sfackler/rust-postgres.git", branch="master"}