#
# NO ACTUAL SECRETS MAY BE PUT HERE FOR NOW
# -----------------------------------------
#
# This file is checked into version control. If we need 'real' secrets later,
# the file must be removed from VC.
#
# The current settings are public and intented for the current public Shuttle
# hosting environment
#
ISSUER_URL='https://lemur-5.cloud-iam.com/auth/realms/verishda'
FORWARDED_PROTO='https'
RUST_LOG='trace'