name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile and release
        run: cargo build --verbose --release
      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-release
          path: ${{ matrix.target }}/target/release/
          retention-days: 30