import { StandardTableView , HorizontalBox, VerticalBox, ComboBox, Button, GroupBox, TextEdit} from "std-widgets.slint";

export enum AnnouncementModel {
    NotAnnounced,
    PresenceAnnounced,
    RecurringPresenceAnnounced,
}

export struct PersonModel {
    name: string,
    user_id: string,
    is_self: bool,
    is_present: bool,
    is_favorite: bool,
    announcements: [AnnouncementModel],
}

export struct SiteModel {
    name: string,
    id: string,
}

component NameDisplay inherits HorizontalLayout {
    in property <PersonModel> person;

    Text {
        horizontal-alignment: left;
        vertical-alignment: center;
        text: person.name;
        font-italic: person.is_self;
    }
}

component FavStar inherits Image {
    in property <bool> is-favorite: false;
    in property <bool> is-self: false;

    callback favorite_change_requested();

    image-fit: ImageFit.contain;

    width: 16px;
    height: 16px;
    touch:= TouchArea {
        clicked => {
            favorite_change_requested();
        }
    }

    states [
        is_favorite when self.is_favorite: {
            source: @image-url("icons/star.svg");
        }
        not_favorite_hover when touch.has-hover && !self.is-favorite && !self.is-self: {
            source: @image-url("icons/star_hollow.svg");
        }
        not_favorite when !touch.has-hover && !self.is_favorite: {
        }
    ]

    
}
component PresenceCell inherits VerticalLayout {
    width: 30px;
}

component PresenceHeaderCell inherits PresenceCell {
    in property <string> text;

    Text {
        horizontal-alignment: center;
        text: parent.text;
    }
}

component PresenceItem inherits PresenceCell{
    in property <bool> read_only;
    in property <bool> is_present;
    in-out property <PersonModel> person;
    in property <int> day-offset;
    property <AnnouncementModel> announcement: person.announcements[day-offset];

    callback announcement_change_requested(PersonModel, int);

    TouchArea {
        x: 0;
        width: parent.width;
        Text {
            horizontal-alignment: center;
            text: is-present ? "P" : 
                announcement == AnnouncementModel.PresenceAnnounced ? "A" : 
                announcement == AnnouncementModel.RecurringPresenceAnnounced ? "R" :
                "-"
            ;
        }
        double-clicked => {
            if read_only {
                return;
            }
            // double click switches for recurring announcement
            person.announcements[day-offset] = AnnouncementModel.RecurringPresenceAnnounced;
            announcement_change_requested(person, day-offset);
        }
        clicked => {
            if read_only {
                return;
            }
            // switch between not announced and announcement requested.
            // recurring announcements are also switched to not announced on click
            person.announcements[day-offset] = person.announcements[day-offset] == AnnouncementModel.NotAnnounced 
                ?   AnnouncementModel.PresenceAnnounced
                :   AnnouncementModel.NotAnnounced;
            announcement_change_requested(person, day-offset);
        }
    }
}

component PresenceGrid {
    in property <[PersonModel]> persons;
    in property <int> current_day_index;

    property <[string]> day_names: [@tr("Mo"), @tr("Tu"), @tr("We"), @tr("Th"), @tr("Fr"), @tr("Sa"), @tr("Su")];

    callback announcement_change_requested(PersonModel, int);
    callback favorite_change_requested(PersonModel);

    function day_index(day_offset: int) -> int {
        Math.mod(day_offset + current-day-index, 7)
    }

    VerticalLayout {
        HorizontalLayout {
            alignment: end;
            for day_offset in 7: PresenceHeaderCell {
                alignment: end;
                text: day_names[day_index(day_offset)];
            }
        }
        for p in persons: HorizontalLayout {
            HorizontalLayout {
                FavStar {
                    height: 20px;
                    horizontal-alignment: left;
                    is-favorite: p.is-favorite;
                    is-self: p.is-self;

                    favorite_change_requested => {
                        favorite_change_requested(p)
                    }
                }
                n:= NameDisplay {
                    person: p;
                    alignment: LayoutAlignment.start;
                }
            }
        
            for day_offset in 7: PresenceItem {
                is_present: day_offset == 0 && p.is_present;
                person: p;
                day-offset: day-offset;
                read_only: !p.is-self;
                announcement_change_requested(p, day-offset) => {
                    root.announcement_change_requested(p, day-offset);
                }
            }
        }
    }
}


export component SitePresenceView inherits Window {

    in property <[PersonModel]> persons: [
        {name: "Uwe Pachler", is-present: true, is_self: true, is-favorite: true},
        {name: "Horst Cresi", is-favorite: true, announcements: [
            AnnouncementModel.NotAnnounced, AnnouncementModel.PresenceAnnounced, AnnouncementModel.NotAnnounced, AnnouncementModel.NotAnnounced, AnnouncementModel.RecurringPresenceAnnounced
        ]},
        {name: "Brian Nürnberg"},
    ];

    in-out property <[SiteModel]> sites: [
        {name: "Stuttgart", id: "stuttgart"},
        {name: "Reutlingen", id: "reutlingen"},
        {name: "Jeverstrasse", id: "jeverstrasse"},
    ];

    in property <[string]> site_names: [
        "Stuttgart",
        "Reutlingen",
        "Jeverstrasse",
    ];

    in property <bool> loading: false;

    in property <int> current_day_index;

    out property <string> selected_site_id;

    callback site_selected(string);
    callback favorite_change_requested(string, bool);
    callback refresh_requested();
    callback announcement_change_requested(string, PersonModel, int);
    callback filter_set(string, bool);

    out property <string> current_site_id <=> panel.current_site_id;

    panel := VerticalLayout { 
        alignment: start;

        out property <string> current_site_id <=> top_bar.current_site_id;
        
        top_bar := HorizontalLayout {
            spacing: 5px;
            out property <string> current_site_id <=> site_combo.current_site_id;

            favfilter_button := Button {
                checkable: true;
                states [
                    checked when self.checked: {
                        icon: @image-url("icons/star.svg");
                    }
                    unchecked when !self.checked: {
                        icon: @image-url("icons/star_hollow.svg");
                    }
                ]
                
                clicked => {
                    filter_set(search-text.text, self.checked);
                }
            }
            Button {
                icon: @image-url("icons/reload.svg");
                clicked => {
                    root.refresh_requested();
                }
            }
            search_button := Button {
                checkable: true;
                icon: @image-url("icons/search.svg");
                clicked => {
                    if !self.checked {
                        search-text.text = "";
                        filter_set("", favfilter-button.checked);
                    }
                    search-text.focus();
                    root.refresh_requested();
                }
            }
            site_search := GridLayout{
                
                search_group:= HorizontalLayout {
                    row: 0;
                    Text {
                        text: "Person: ";
                        vertical-alignment: center;
                        horizontal-stretch: 0;
                    }
                    search_text := TextInput {
                        text: "";
                        vertical-alignment: center;
                        horizontal-stretch: 1;

                        edited => {
                            filter_set(self.text, favfilter-button.checked);
                        }
                    }
                    horizontal-stretch: 1;
                }
                
                
                site_combo := ComboBox {
                    row: 0;
                    out property <string> current_site_id;
        
                    function get_current_site_id() -> string {
                        self.current-index >= 0 ? sites[self.current-index].id : ""
                    } 
        
                    model: site_names;
                    selected(name) => {
                        self.current_site_id = get_current_site_id();
                        root.site_selected(get_current_site_id())
                    }
                }
            }

            states [
                choose-site when !search-button.checked: {
                    search_group.visible: false;
                    site_combo.visible: true;
                }
                search-site when search-button.checked: {
                    search_group.visible: true;
                    site_combo.visible: false;
                }
            ]
            
        }


        if persons.length > 0:
            PresenceGrid {
                // example data; this will have to be set in code later
                current-day-index: root.current_day_index;
                persons: persons;
                announcement_change_requested(p,n) => {
                    announcement_change_requested(current_site_id, p,n);
                }
                favorite_change_requested(p) => {
                    favorite_change_requested(p.user_id, !p.is-favorite);
                }
            }
        
        if persons.length == 0:
            Text{
                text: @tr("No people registered at site");
                horizontal-alignment: center;
            }
    } 
}